services:
  app:
    build:
      context: .
    env_file:
      - ./.env.local
    volumes:
      - ./dora_person:/usr/src/app/dora_person
      - socket:/var/tmp
    depends_on:
      redis:
        condition: service_started
  redis:
    image: "redis:alpine"
  web:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - socket:/var/tmp
    depends_on:
      - app
volumes:
  socket:
