services:
  app:
    build:
      context: .
    env_file:
      - ./.env.local
    volumes:
      - ./dora_person:/usr/src/app/dora_person
      - socket:/var/tmp
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_started
  redis:
    image: "redis:alpine"
  web:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - socket:/var/tmp
    depends_on:
      - app
  mysql:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: dora_root_pw
      MYSQL_DATABASE: dora_person
    cap_add:
      - SYS_NICE

volumes:
  socket:
  db_data:
